### ISSUE TITLE
facebook locked my account at first login attempt

### ISSUE THREAD

**Issue by egils-consulting** [AstroCB/Messenger-CLI#20]
Hi, I attempted to run the script. It seems facebook can detect its a script and subsequently locked my account. Thats really bad.

**Comment by egils-consulting** [comment]
I think the use of facebook-chat-api is the problem. It has not been reviewed and facebook does not like that at all. See https://developers.facebook.com/docs/permissions/reference/pages_messaging for details about the review / permissions.

**Comment by AstroCB** [comment]
Yes – this is true. All of my Messenger projects use facebook-chat-api in order to use functionality from Messenger that is not available with their official first-party API. I should mention that in the readme for this project – this is very much an experimental dev tool, rather than a production application intended for regular usage.

There are some steps taken to reduce the occurrence of account locks (which should be pretty easily resolved in most cases), but it is an inherent risk needed for this project to even exist. If you're looking for a tool to message as pages, I'm sure there are others available that use the official API, but this one is primary intended to operate on a user account.

**Comment by egils-consulting** [comment]
Could you point me in the direction of such an official tool?
Also I think its wise to mention in the readme what you just wrote. I cannot risk getting locked out as I need to communicate with customers.

**Comment by AstroCB** [comment]
Unfortunately I'm not aware of any as I've never had that use case. I'll definitely update the readme.

**Comment by egils-consulting** [comment]
I searched github extensively and found none unfortunately. I'll have to make my own it seems, I just need the notification so that won't be so hard I hope.
