### ISSUE TITLE
Messenger CLI will show wrong username/password despite credentials being correct and 2fa being turned off

### ISSUE THREAD

**Issue by longboarder241** [AstroCB/Messenger-CLI#22]
Is the API expired or am I missing something here? the whole application installed properly

**Comment by AstroCB** [comment]
Yes, unfortunately [the underlying API](github.com/Schmavery/facebook-chat-api) is no longer maintained and that makes logging in with it unreliable. Not much to be done since Facebook continues to shut down any fixes that are made, but you may be able to find some temporary workarounds in the issues of that repo.
