### ISSUE TITLE
Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response

### ISSUE THREAD

**Issue by KonradLinkowski** [AstroCB/Messenger-CLI#9]
Everything freezes when I write anything after logging in and then I've got Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response followed by a long stack trace.

**Comment by AstroCB** [comment]
Looks like the listening functions need to be migrated over to the [new GraphQL endpoint](https://github.com/Schmavery/facebook-chat-api/issues/487).

**Comment by AstroCB** [comment]
I moved over the functions to the GraphQL endpoints, but it appears `getThreadList` is broken, and the code relies pretty heavily upon that function, [as I see you've noticed](https://github.com/Schmavery/facebook-chat-api/issues/605).

**Comment by AstroCB** [comment]
I've updated the functions to use the GraphQL endpoints, but unfortunately due to its dependence on `getThreadList`, the CLI won't be of much use until [this PR](https://github.com/Schmavery/facebook-chat-api/pull/572) is merged, as I can see [you've noticed](https://github.com/Schmavery/facebook-chat-api/issues/605).

**Comment by bsansouci** [comment]
Does this work now?

**Comment by AstroCB** [comment]
Yep -- just needed to do some updating since the field names changed, but everything should work now. Thanks guys!

**Comment by AstroCB** [comment]
Yep – just needed to do some updating since the field names changed, but everything should work now. Thanks guys!
